### PR TITLE
Update ostree, flatpak and flatpak-builder

### PR DESCRIPTION
**Pull request by bochecha**
In particular, f-b is required to get Totem to build again.

### CODE REVIEW

**Comment by alatiera** [comment]
ROFL, this is the same as #18 essentially but 2 days younger!

**Comment by bochecha** [comment]
No, it's not exactly the same, because I'm updating to a git snapshot of flatpak-builder, which is needed to fix Totem.

**Comment by alatiera** [comment]
> No, it's not exactly the same, because I'm updating to a git snapshot of flatpak-builder, which is needed to fix Totem.

Thought that was included in f-b 1.0.4?

**Comment by bochecha** [comment]
> Thought that was included in f-b 1.0.4?

No it's not, otherwise I'd have used the tag here.

**Pull request merged**
